/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingRouteImport } from './routes/_app.setting'
import { Route as AppPemakaianRouteImport } from './routes/_app.pemakaian'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBarangProsesRouteImport } from './routes/_app.barang-proses'
import { Route as AppBarangPerjalananRouteImport } from './routes/_app.barang-perjalanan'
import { Route as AppBarangJadiRouteImport } from './routes/_app.barang-jadi'
import { Route as AppBahanBakuRouteImport } from './routes/_app.bahan-baku'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingRoute = AppSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AppRoute,
} as any)
const AppPemakaianRoute = AppPemakaianRouteImport.update({
  id: '/pemakaian',
  path: '/pemakaian',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBarangProsesRoute = AppBarangProsesRouteImport.update({
  id: '/barang-proses',
  path: '/barang-proses',
  getParentRoute: () => AppRoute,
} as any)
const AppBarangPerjalananRoute = AppBarangPerjalananRouteImport.update({
  id: '/barang-perjalanan',
  path: '/barang-perjalanan',
  getParentRoute: () => AppRoute,
} as any)
const AppBarangJadiRoute = AppBarangJadiRouteImport.update({
  id: '/barang-jadi',
  path: '/barang-jadi',
  getParentRoute: () => AppRoute,
} as any)
const AppBahanBakuRoute = AppBahanBakuRouteImport.update({
  id: '/bahan-baku',
  path: '/bahan-baku',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bahan-baku': typeof AppBahanBakuRoute
  '/barang-jadi': typeof AppBarangJadiRoute
  '/barang-perjalanan': typeof AppBarangPerjalananRoute
  '/barang-proses': typeof AppBarangProsesRoute
  '/dashboard': typeof AppDashboardRoute
  '/laporan': typeof AppLaporanRoute
  '/pemakaian': typeof AppPemakaianRoute
  '/setting': typeof AppSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bahan-baku': typeof AppBahanBakuRoute
  '/barang-jadi': typeof AppBarangJadiRoute
  '/barang-perjalanan': typeof AppBarangPerjalananRoute
  '/barang-proses': typeof AppBarangProsesRoute
  '/dashboard': typeof AppDashboardRoute
  '/laporan': typeof AppLaporanRoute
  '/pemakaian': typeof AppPemakaianRoute
  '/setting': typeof AppSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bahan-baku': typeof AppBahanBakuRoute
  '/_app/barang-jadi': typeof AppBarangJadiRoute
  '/_app/barang-perjalanan': typeof AppBarangPerjalananRoute
  '/_app/barang-proses': typeof AppBarangProsesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/pemakaian': typeof AppPemakaianRoute
  '/_app/setting': typeof AppSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bahan-baku'
    | '/barang-jadi'
    | '/barang-perjalanan'
    | '/barang-proses'
    | '/dashboard'
    | '/laporan'
    | '/pemakaian'
    | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bahan-baku'
    | '/barang-jadi'
    | '/barang-perjalanan'
    | '/barang-proses'
    | '/dashboard'
    | '/laporan'
    | '/pemakaian'
    | '/setting'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bahan-baku'
    | '/_app/barang-jadi'
    | '/_app/barang-perjalanan'
    | '/_app/barang-proses'
    | '/_app/dashboard'
    | '/_app/laporan'
    | '/_app/pemakaian'
    | '/_app/setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/setting': {
      id: '/_app/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AppSettingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pemakaian': {
      id: '/_app/pemakaian'
      path: '/pemakaian'
      fullPath: '/pemakaian'
      preLoaderRoute: typeof AppPemakaianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barang-proses': {
      id: '/_app/barang-proses'
      path: '/barang-proses'
      fullPath: '/barang-proses'
      preLoaderRoute: typeof AppBarangProsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barang-perjalanan': {
      id: '/_app/barang-perjalanan'
      path: '/barang-perjalanan'
      fullPath: '/barang-perjalanan'
      preLoaderRoute: typeof AppBarangPerjalananRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barang-jadi': {
      id: '/_app/barang-jadi'
      path: '/barang-jadi'
      fullPath: '/barang-jadi'
      preLoaderRoute: typeof AppBarangJadiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bahan-baku': {
      id: '/_app/bahan-baku'
      path: '/bahan-baku'
      fullPath: '/bahan-baku'
      preLoaderRoute: typeof AppBahanBakuRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBahanBakuRoute: typeof AppBahanBakuRoute
  AppBarangJadiRoute: typeof AppBarangJadiRoute
  AppBarangPerjalananRoute: typeof AppBarangPerjalananRoute
  AppBarangProsesRoute: typeof AppBarangProsesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppPemakaianRoute: typeof AppPemakaianRoute
  AppSettingRoute: typeof AppSettingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBahanBakuRoute: AppBahanBakuRoute,
  AppBarangJadiRoute: AppBarangJadiRoute,
  AppBarangPerjalananRoute: AppBarangPerjalananRoute,
  AppBarangProsesRoute: AppBarangProsesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppPemakaianRoute: AppPemakaianRoute,
  AppSettingRoute: AppSettingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
